server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs
  - job_name: mom-kidz-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: mom-kidz
          service: app
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - labels:
          level:
          message:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Care Log specific logs
  - job_name: care-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: mom-kidz
          service: care-log
          __path__: /var/log/care-log/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            user_id: user_id
            activity_type: activity_type
            timestamp: timestamp
      - labels:
          level:
          user_id:
          activity_type:
      - timestamp:
          source: timestamp
          format: RFC3339

  # API logs
  - job_name: mom-kidz-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: mom-kidz
          service: api
          __path__: /var/log/api/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            method: method
            path: path
            status: status
            duration: duration
            timestamp: timestamp
      - labels:
          level:
          method:
          path:
          status:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Authentication logs
  - job_name: mom-kidz-auth
    static_configs:
      - targets:
          - localhost
        labels:
          job: mom-kidz
          service: auth
          __path__: /var/log/auth/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            user_id: user_id
            event: event
            timestamp: timestamp
      - labels:
          level:
          user_id:
          event:
      - timestamp:
          source: timestamp
          format: RFC3339

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>[^ ]* [^ ]*) (?P<host>[^ ]*) (?P<component>[^:]*): (?P<message>.*)'
      - labels:
          host:
          component:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
