groups:
  - name: care-log-alerts
    rules:
      - alert: CareLogEntryDecrease
        expr: rate(care_log_entries_total[6h]) < histogram_quantile(0.1, rate(care_log_entries_bucket[24h]))
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Care log entries have decreased significantly"
          description: "The rate of care log entries is lower than usual"

      - alert: MissingDailyCareLog
        expr: time() - max(care_log_last_entry) by (user_id) > 86400
        for: 12h
        labels:
          severity: warning
        annotations:
          summary: "Users missing daily care log entries"
          description: "Some users haven't logged any care activities in the last 24 hours"

      - alert: CareLogSyncIssues
        expr: rate(care_log_sync_failures_total[15m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Care log synchronization issues detected"
          description: "Care log entries are failing to sync"

      - alert: AnomalousCareLogPattern
        expr: abs(rate(care_log_entries_total[1h]) - avg_over_time(rate(care_log_entries_total[1h])[24h:1h])) > 3 * stddev_over_time(rate(care_log_entries_total[1h])[24h:1h])
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Unusual care log pattern detected"
          description: "Care log entry pattern deviates significantly from normal"

  # Recording rules for care log metrics
  - name: care-log-recordings
    rules:
      - record: job:care_log_entries:rate5m
        expr: rate(care_log_entries_total[5m])

      - record: job:care_log_entries:daily
        expr: sum(increase(care_log_entries_total[24h])) by (type)

      - record: job:care_log_completion:ratio
        expr: sum(care_log_completed) / sum(care_log_total)

      - record: job:care_log_streak:avg
        expr: avg(care_log_streak_days) by (user_tier)
