apiVersion: 1

datasources:
  - name: Supabase
    type: postgres
    url: ${SUPABASE_DB_HOST}:${SUPABASE_DB_PORT}
    user: ${SUPABASE_DB_USER}
    secureJsonData:
      password: ${SUPABASE_DB_PASSWORD}
    jsonData:
      database: ${SUPABASE_DB_NAME}
      sslmode: require
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    editable: false
    isDefault: true